# Generated by Django 2.2 on 2019-12-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_ingredient_steps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
    ]
